let fs = require('fs')
let handler = async (m) => {
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
let spams = fs.readFileSync('./sticker/spams.webp')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
conn.fakeReply(m.chat, spams, '*MENGERROR*', 'status@broadcast')
}
handler.help = ['']
handler.tags = ['spam']
handler.command = /^()$/i

handler.owner = false
handler.mods = true
handler.premium = false
handler.group = true
handler.private = false

module.exports = handler